server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  amqp:
    deserialization:
      trust:
        all: true

core:
  queue: core-fila-de-candidatos
  node-id: RASTAFARI
