server:
  port: 8080

spring:
  rabbitmq:
    host: chimpanzee.rmq.cloudamqp.com
    port: 5671
    username: edxgujmk
    password: Wm1vy2ea99LIfZh-ZZyl3DhWlLDlNcdH
    virtual-host: edxgujmk
    ssl:
      enabled: true
  amqp:
    deserialization:
      trust:
        all: true

core:
  queue: lotes_de_dados
  node-id: RASTAFARI
